title:            Craig French
subtitle:		  Philosopher - Cambridge University
description:      Philosopher Cambridge University
image:			  /img/Portrait.jpg
url:			  http://craigafrench.github.io

name: 	Craig French
email: 	craig@craigfrench.co.uk

# CV location
cv:			/assets/CraigFrenchCV.pdf

# Social media / online presence
twitter:	earlymodphil
instagram:	craigfrench1
flickr:		craigafrench
