title:            Craig French
subtitle:		  Philosopher - Cambridge University
description:      Philosopher Cambridge University
image:			  https://dl.dropboxusercontent.com/u/3913409/Site%20Content/1.jpg
url:			  http://craigafrench.github.io

name: 	Craig French
email: 	craig@craigfrench.co.uk

# CV location (I envisage a PDF file here)
cv:			https://dl.dropboxusercontent.com/u/3913409/Site%20Content/CraigFrenchCV.pdf

# Social media / online presence
twitter:	earlymodphil