title:            Craig French
subtitle:		  Philosopher - University of Nottingham
description:      Philosopher University of Nottingham
image: http://craigafrench.github.io/img/1.jpg
url:			  http://craigafrench.github.io

name: 	Craig French
email: 	craig@craigfrench.co.uk

# Google Analytics
google_analytics: 	UA-66399450-1
google_verify: 		UA-66399450-1

# CV location
cv:			/assets/CraigFrenchCV.pdf

# Social media / online presence
twitter:	craigafrench
instagram:	craigfrench1
flickr:		craigfrench

