title:            Craig French
subtitle:		  Philosopher - Cambridge University
description:      Philosopher Cambridge University
image: http://craigafrench.github.io/img/Portrait1.png
url:			  http://craigafrench.github.io

name: 	Craig French
email: 	craig@craigfrench.co.uk

# Google Analytics
google_analytics: 	UA-66399450-1
google_verify: 		UA-66399450-1

# CV location
cv:			/assets/CraigFrenchCV.pdf

# Social media / online presence
twitter:	earlymodphil
instagram:	craigfrench1
flickr:		craigfrench

